name: BPM MLOps Pipeline

on:
  push:
    branches:
      - main
  # schedule:
  #   # Every 5 minutes (for testing purposes)
  #   - cron: "*/5 * * * *"

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SCORING_URI: ${{ secrets.SCORING_URI }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install azureml-core azureml-sdk pandas scikit-learn joblib requests

    - name: Azure ML Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # Step1: Training locally
    - name: Run training
      run: |
        python main.py --train-data-path data/train.csv --test-data-path data/test.csv

      # Step2: Upload dataset, submit training job and register model
    - name: Register model
      run: |
        python deployment/azureml_train_deploy.py

      # Step3: Deploy model
    - name: Deploy Model
      run: |
        python deployment/deploy_model.py
      
      # Step 4: Run test predictions (optional)  
    - name: Predict new songs (test)
      run: |
        export SCORING_URI=${{ secrets.SCORING_URI }}
        export API_KEY=${{ secrets.API_KEY }}
        python scripts/automate_predictions.py --input scripts/automate_predictions_test_data.csv
        
